apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: activemq
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    repoURL: http://192.168.132.27/devops/helm-charts.git
    path: charts/activemq
    targetRevision: HEAD
    helm:
      values: |
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
