apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    path: charts/mysql
    repoURL: http://192.168.132.27/devops/helm-charts.git
    targetRevision: HEAD
    helm:
      values: |
        mysql:
          busybox:
            tag: latest
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
